ButtonGrid/Models/ButtonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ButtonGrid.Models
{
    public class ButtonModel
    {
        public int Id { get; set; }
        public int ButtonState { get; set; }
    }
}

ButtonGrid/Models/ErrorViewModel.cs
using System;

namespace ButtonGrid.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ButtonGrid/Controllers/ButtonController.cs
using ButtonGrid.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ButtonGrid.Controllers
{
    public class ButtonController : Controller
    {
        static List<ButtonModel> buttons = new List<ButtonModel>();
        Random random = new Random();
        const int GRID_SIZE = 25;

        public IActionResult Index()
        {
            if (buttons.Count < GRID_SIZE)
            {
                for (int i = 0; i < GRID_SIZE; i++)
                {
                    buttons.Add(new ButtonModel { Id = i, ButtonState = random.Next(4) });
                }
            }
            
            

            return View("Index", buttons);
        }

        public IActionResult HandleButtonClick(string buttonNumber)
        {
            int bn = int.Parse(buttonNumber);
            buttons.ElementAt(bn).ButtonState = (buttons.ElementAt(bn).ButtonState + 1)%4;
            return View("Index", buttons);
        }


        public IActionResult ShowOneButton(int buttonNumber)
        {
            buttons.ElementAt(buttonNumber).ButtonState = (buttons.ElementAt(buttonNumber).ButtonState + 1) % 4;
            return PartialView(buttons.ElementAt(buttonNumber));
        }

        public IActionResult RightClickShowOneButton(int buttonNumber)
        {
            buttons.ElementAt(buttonNumber).ButtonState = 0;
            return PartialView("ShowOneButton", buttons.ElementAt(buttonNumber));
        }
    }

    
}

ButtonGrid/Controllers/HomeController.cs
using ButtonGrid.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ButtonGrid.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ButtonGrid/Views/Button/Index.cshtml
@model IEnumerable<ButtonGrid.Models.ButtonModel>

<style>
    .game-button {
        width:75px;
        text-align:center;
        border:none;
    }
    .game-button-image{
        width:70%;
    }
    .button-zone{
        display:flex;
        flex-wrap:wrap;
    }
    .line-break{
        flex-basis:100%;
        height:0;
    }
    .button-label{
        font-size:8px;
        text-align:center;
    }

</style>

@{ 
    string[] imagenames = { "BlueButton.png", "GreenButton.png", "OrangeButton.png", "PinkButton.png" };
}
<p>Current Time: @DateTime.Now</p>
<form>
    <div class="button-zone">

        @for (int i = 0; i < Model.Count(); i++)
        {
            //start newe line every five elements
            if (i % 5 == 0)
            {
                <div class="line-break"></div>
            }
        <div class="oneButton" id=@i>
            <button class="game-button" name="buttonNumber" value="@Model.ElementAt(i).Id" type="submit" asp-controller="button" asp-action="HandleButtonClick">
                <img class="game-button-image" src="~/img/@imagenames[Model.ElementAt(i).ButtonState]" />

                <div class="button-label">
                    @Model.ElementAt(i).Id, @Model.ElementAt(i).ButtonState
                </div>
            </button>
        </div>

            

        }
    </div>
</form>

ButtonGrid/Views/Button/ShowOneButton.cshtml
@model ButtonGrid.Models.ButtonModel

@{
    string[] imagenames = { "BlueButton.png", "GreenButton.png", "OrangeButton.png", "PinkButton.png" };
}

<button class="game-button" name="buttonNumber" value="@Model.Id" type="submit" asp-controller="button" asp-action="HandleButtonClick">
    <img class="game-button-image" src="~/img/@imagenames[Model.ButtonState]" />

    <div class="button-label">
        @Model.Id, @Model.ButtonState
    </div>
</button>

ButtonGrid/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ButtonGrid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ButtonGrid</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ButtonGrid</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Button" asp-action="Index">Button Grid</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ButtonGrid - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>