BibleVerses/Models/ErrorViewModel.cs
using System;

namespace BibleVerses.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BibleVerses/Models/VerseModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace BibleVerses.Models
{
    public class VerseModel
    {
        //Id number for each verse
        [DisplayName("ID Number")]
        public int Id { get; set; }
        //The book each verse is contained within, in chronological order
        [DisplayName("Book")]
        public int Book { get; set; }
        //The chapter each verse is contained within, in chronological order
        [DisplayName("Chapter")]
        public int Chapter { get; set; }
        //specified number for each verse
        [DisplayName("Verse Number")]
        public int VerseNum { get; set; }
        //verse text 
        [DisplayName("Text")]
        public string VerseText { get; set; }
    }
}

BibleVerses/Controllers/HomeController.cs
using BibleVerses.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BibleVerses.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BibleVerses/Controllers/VerseController.cs
using BibleVerses.Models;
using BibleVerses.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BibleVerses.Controllers
{
    public class VerseController : Controller
    {
        //Data Access Object available to all class methods
        VersesDAO vDAO = new VersesDAO(); 

        //Displays all verses returned from the DAO
        public IActionResult Index()
        {
            return View("Index", vDAO.GetAllVerses());
        }

        //Displays the search form view
        public IActionResult SearchForm()
        {
            return View();
        }

        //Loads the Verse Index view specifically awaiting a get request
        [HttpGet]
        public IActionResult SearchResults(string searchTerm, int search_section)
        {
            List<VerseModel> searchList = vDAO.SearchAllVerses(searchTerm, search_section);
            return View("Index", searchList);
        }
    }
}

BibleVerses/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BibleVerses/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BibleVerses</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BibleVerses</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Verse" asp-action="SearchForm">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BibleVerses - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BibleVerses/Views/Verse/Index.cshtml
@model IEnumerable<BibleVerses.Models.VerseModel>

<p>
    <a asp-action="Create">Verses</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Chapter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VerseNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VerseText)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Book)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Chapter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VerseNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VerseText)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

BibleVerses/Views/Verse/SearchForm.cshtml
@model BibleVerses.Models.VerseModel

<h4>Search Form</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SearchResults" method="get">

            <div class="form-group">
                <label class="control-label">Search for a Bible Verse:</label>
                <input name="searchTerm" class="form-control" />
            </div>
            <div class="form-group">
                <input type="radio" id="both" name="search_section" value="0" checked>
                <label for="both">Both</label><br>
                <input type="radio" id="ot" name="search_section" value="1">
                <label for="ot">Old Testament</label><br>
                <input type="radio" id="nt" name="search_section" value="2">
                <label for="nt">New Testament</label>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>